version: '3.8'

services:
    api:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_CONNECTION_STRING: "Server=db;Port=3306;Database=FoodDeliveryDb;User=root;Password=root;AllowPublicKeyRetrieval=True;"
            ASPNETCORE_ENVIRONMENT: "Development"
        restart: always

    db:
        image: "mysql:8.0"
        container_name: food_delivery_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "FoodDeliveryDb"
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysql", "-uroot", "-proot", "-e", "SELECT 1"]
            interval: 10s
            retries: 5
            timeout: 5s